version: '3'

services:
  web:
    build: app/
    ports:
      - "8000:8000"
    volumes:
      - ./web_volume:/app
    depends_on:
      - db
      - s3
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - ./db_volume:/var/lib/postgresql/data/

  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    environment:
      - ENABLE_BASIC_AUTH=true
      - AWS_ACCESS_KEY_ID=your_access_key
      - AWS_SECRET_ACCESS_KEY=your_secret_key
    volumes:
      - ./s3_volume:/fakes3_root/s3/s3


volumes:
  db_volume:
  s3_volume:
  web_volume:
