version: '3'

services:
  web:
    build: app/
    ports:
      - "8000:8000"
    volumes:
      - ./web_volume:/competitors
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    volumes:
      - ./db_volume:/var/lib/postgresql/data/


volumes:
  db_volume:
  web_volume:
